### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/dna-monitor#20]

**Comment by hobbyquaker** [comment]
hmm... i think we don't need that - on windows one can use Escribe. If someone wants a windows release pls reopen this issue.

**Comment by helluvamatt** [comment]
I would like Windows support because EScribe samples at 1-2Hz. One of their devs commented in the Evolv forums that this was because the Serial port sampling is on the same thread as the WinForms drawing.

I will clone the repo and work on it myself and submit a pull request when I figure it out.
