### ISSUE TITLE
Some commands

### ISSUE THREAD

**Issue by dywersant** [hobbyquaker/dna-monitor#7]
Hi, some raw code i pulled from Escribe, might be useful.
[snip1](http://paste.ofcode.org/3an7FSwUsCCRz5ujsFPtiSi)
[snip2](http://paste.ofcode.org/a24UszbLvfaJM3dDvVXxvV)

**Comment by hobbyquaker** [comment]
Wow nice, big thx 👍

**Comment by hobbyquaker** [comment]
I started a documentation of all known commands here:
https://github.com/hobbyquaker/dna-commands

**Comment by dywersant** [comment]
Great work sir, shame on Evolv for ditching Mac users :+1:

**Comment by pokjvghcbv** [comment]
Looks like a USB snoop, including fields from their debug window. Wayneo on the forum. 

Sebastian, I'll start working on a rough user manual if you wish. 

I see Power and temp are static display fields, the others not.

**Comment by hobbyquaker** [comment]
sure, I appreciate any kind of participation here :)
Just make Pull-Requests against the Readme file, if you need help with Github or Markdown files don't hesitate to ask.
